# docker-compose.yml
version: "3"
services:
  app:
    container_name: app
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules
    networks:
      - api_nw
      - api_db
  
  front-end:
    container_name: front-end
    build: ./frontend
    ports:
      - 80:80
    networks:
      - api_nw
    volumes:
      - ./frontend/:/var/www

  evil-front-end: 
    container_name: evil-front-end
    build: ./evil-frontend
    ports:
      - 81:80
      
  postgres:
    container_name: postgres
    image: postgres:10.4
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    networks:
      - api_db
      
networks:
  api_nw:
    driver: bridge
  api_db:
    driver: bridge